// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pools.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getPoolsbyTags = `-- name: GetPoolsbyTags :many
SELECT pool.id FROM pool
WHERE pool.tag = ANY($1::text[])
`

func (q *Queries) GetPoolsbyTags(ctx context.Context, dollar_1 []string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getPoolsbyTags, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
