// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pools.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addCountry = `-- name: AddCountry :one
INSERT INTO country(name,code,region_id)
VALUES($1,$2,$3)
RETURNING id, name, code, region_id, created_at, updated_at
`

type AddCountryParams struct {
	Name     string
	Code     string
	RegionID uuid.UUID
}

func (q *Queries) AddCountry(ctx context.Context, arg AddCountryParams) (Country, error) {
	row := q.db.QueryRowContext(ctx, addCountry, arg.Name, arg.Code, arg.RegionID)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.RegionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addRegion = `-- name: AddRegion :one
INSERT INTO region(name)
VALUES($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) AddRegion(ctx context.Context, name string) (Region, error) {
	row := q.db.QueryRowContext(ctx, addRegion, name)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addUpstream = `-- name: AddUpstream :one
INSERT INTO upstream(tag,upstream_provider,format,port,domain)
VALUES($1,$2,$3,$4,$5)
RETURNING id, tag, upstream_provider, format, port, domain, created_at, updated_at
`

type AddUpstreamParams struct {
	Tag              string
	UpstreamProvider string
	Format           string
	Port             int32
	Domain           string
}

func (q *Queries) AddUpstream(ctx context.Context, arg AddUpstreamParams) (Upstream, error) {
	row := q.db.QueryRowContext(ctx, addUpstream,
		arg.Tag,
		arg.UpstreamProvider,
		arg.Format,
		arg.Port,
		arg.Domain,
	)
	var i Upstream
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.UpstreamProvider,
		&i.Format,
		&i.Port,
		&i.Domain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCountry = `-- name: DeleteCountry :exec
DELETE FROM country as c
where c.name = $1
`

func (q *Queries) DeleteCountry(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCountry, name)
	return err
}

const deleteRegion = `-- name: DeleteRegion :exec
DELETE FROM region as r
where r.name = $1
`

func (q *Queries) DeleteRegion(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRegion, name)
	return err
}

const deleteUpstream = `-- name: DeleteUpstream :exec
DELETE FROM upstream as u
where u.id = $1
`

func (q *Queries) DeleteUpstream(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUpstream, id)
	return err
}

const getCountries = `-- name: GetCountries :many
SELECT id, name, code, region_id, created_at, updated_at FROM country
`

func (q *Queries) GetCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.QueryContext(ctx, getCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Country
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.RegionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRegions = `-- name: GetRegions :many
SELECT id, name, created_at, updated_at FROM region
`

func (q *Queries) GetRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.QueryContext(ctx, getRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpstreams = `-- name: GetUpstreams :many
SELECT id, tag, upstream_provider, format, port, domain, created_at, updated_at FROM upstream
`

func (q *Queries) GetUpstreams(ctx context.Context) ([]Upstream, error) {
	rows, err := q.db.QueryContext(ctx, getUpstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Upstream
	for rows.Next() {
		var i Upstream
		if err := rows.Scan(
			&i.ID,
			&i.Tag,
			&i.UpstreamProvider,
			&i.Format,
			&i.Port,
			&i.Domain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPoolUpstreamWeight = `-- name: InsertPoolUpstreamWeight :many
INSERT INTO pool_upstream_weight (pool_id, weight, upstream_id)
SELECT 
    $1,           -- pool_id (constant)
    T.w,          -- weight (unnested)
    U.id          -- upstream_id (matched by tag)
FROM 
    upstream AS U
JOIN 
    ROWS FROM (UNNEST($2::INT[]), UNNEST($3::text[])) AS T(w, t) 
        ON U.tag = T.t -- Join the parallel (weight, tag) set to upstream based on tag
RETURNING 
    id, pool_id, upstream_id, weight
`

type InsertPoolUpstreamWeightParams struct {
	PoolID  uuid.UUID
	Column2 []int32
	Column3 []string
}

func (q *Queries) InsertPoolUpstreamWeight(ctx context.Context, arg InsertPoolUpstreamWeightParams) ([]PoolUpstreamWeight, error) {
	rows, err := q.db.QueryContext(ctx, insertPoolUpstreamWeight, arg.PoolID, pq.Array(arg.Column2), pq.Array(arg.Column3))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PoolUpstreamWeight
	for rows.Next() {
		var i PoolUpstreamWeight
		if err := rows.Scan(
			&i.ID,
			&i.PoolID,
			&i.UpstreamID,
			&i.Weight,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insetPool = `-- name: InsetPool :one
INSERT INTO pool(name,tag,region_id,subdomain,port)
VALUES($1,$2,$3,$4,$5)
RETURNING id, name, tag, region_id, subdomain, port, created_at, updated_at
`

type InsetPoolParams struct {
	Name      string
	Tag       string
	RegionID  uuid.UUID
	Subdomain string
	Port      int32
}

func (q *Queries) InsetPool(ctx context.Context, arg InsetPoolParams) (Pool, error) {
	row := q.db.QueryRowContext(ctx, insetPool,
		arg.Name,
		arg.Tag,
		arg.RegionID,
		arg.Subdomain,
		arg.Port,
	)
	var i Pool
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tag,
		&i.RegionID,
		&i.Subdomain,
		&i.Port,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPoolsWithUpstreams = `-- name: ListPoolsWithUpstreams :many
SELECT 
    p.id AS pool_id,
    p.name AS pool_name,
    p.tag AS pool_tag,
    p.subdomain AS pool_subdomain,
    p.port AS pool_port,
    u.tag AS upstream_tag,
    u.format AS upstream_format,
    u.port AS upstream_port,
    u.domain AS upstream_domain
FROM pool p
LEFT JOIN pool_upstream_weight puw ON p.id = puw.pool_id
LEFT JOIN upstream u ON puw.upstream_id = u.id
`

type ListPoolsWithUpstreamsRow struct {
	PoolID         uuid.UUID
	PoolName       string
	PoolTag        string
	PoolSubdomain  string
	PoolPort       int32
	UpstreamTag    sql.NullString
	UpstreamFormat sql.NullString
	UpstreamPort   sql.NullInt32
	UpstreamDomain sql.NullString
}

func (q *Queries) ListPoolsWithUpstreams(ctx context.Context) ([]ListPoolsWithUpstreamsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPoolsWithUpstreams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoolsWithUpstreamsRow
	for rows.Next() {
		var i ListPoolsWithUpstreamsRow
		if err := rows.Scan(
			&i.PoolID,
			&i.PoolName,
			&i.PoolTag,
			&i.PoolSubdomain,
			&i.PoolPort,
			&i.UpstreamTag,
			&i.UpstreamFormat,
			&i.UpstreamPort,
			&i.UpstreamDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
