// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pools.sql

package repository

import (
	"context"
)

const addRegion = `-- name: AddRegion :one
INSERT INTO region(name)
VALUES($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) AddRegion(ctx context.Context, name string) (Region, error) {
	row := q.db.QueryRowContext(ctx, addRegion, name)
	var i Region
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRegion = `-- name: DeleteRegion :exec
DELETE FROM region as r
where r.name = $1
RETURNING id, name, created_at, updated_at
`

func (q *Queries) DeleteRegion(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteRegion, name)
	return err
}

const getRegions = `-- name: GetRegions :many
SELECT id, name, created_at, updated_at FROM region
`

func (q *Queries) GetRegions(ctx context.Context) ([]Region, error) {
	rows, err := q.db.QueryContext(ctx, getRegions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Region
	for rows.Next() {
		var i Region
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
