// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddRegion(ctx context.Context, name string) (Region, error)
	AddUserPoolsByPoolTags(ctx context.Context, arg AddUserPoolsByPoolTagsParams) (AddUserPoolsByPoolTagsRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRegion(ctx context.Context, name string) error
	DeleteUserIpwhitelist(ctx context.Context, arg DeleteUserIpwhitelistParams) error
	DeleteUserPoolsByTags(ctx context.Context, arg DeleteUserPoolsByTagsParams) error
	GetAllusers(ctx context.Context) ([]GetAllusersRow, error)
	GetDatausageById(ctx context.Context, id uuid.UUID) (GetDatausageByIdRow, error)
	GetRegions(ctx context.Context) ([]Region, error)
	GetUserIpwhitelistByUserId(ctx context.Context, id uuid.UUID) (GetUserIpwhitelistByUserIdRow, error)
	GetUserPoolsByUserId(ctx context.Context, id uuid.UUID) (GetUserPoolsByUserIdRow, error)
	GetUserbyId(ctx context.Context, id uuid.UUID) (GetUserbyIdRow, error)
	InsertUserIpwhitelist(ctx context.Context, arg InsertUserIpwhitelistParams) ([]UserIpWhitelist, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
