// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetIpWhitelistByUserId(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetPoolsbyTags(ctx context.Context, dollar_1 []string) ([]uuid.UUID, error)
	GetUserPoolByUserId(ctx context.Context, userID uuid.UUID) ([]string, error)
	GetUserbyId(ctx context.Context, id uuid.UUID) (User, error)
	InsertUserIpwhitelist(ctx context.Context, arg InsertUserIpwhitelistParams) ([]UserIpWhitelist, error)
	InsertUserPool(ctx context.Context, arg InsertUserPoolParams) ([]UserPool, error)
}

var _ Querier = (*Queries)(nil)
